### ISSUE TITLE
Background does not load in FF

### ISSUE THREAD

**Issue by kugg** [kugg/SunCitadel#1]
The page seem to render fine in Chrome and WebKit. In FF the background image does not load at all. Investigate by looking at alternative background-image css3 tags. The bug is present in 5ec62b9fa1603f53e9d2047a2429ab119636aab1
![Screenshot from 2019-10-08 12-12-49](https://user-images.githubusercontent.com/53967/66387803-fe404f00-e9c4-11e9-95bf-30eb66cedb3a.png)

**Comment by Amaris7** [comment]
Verified, closing..

**Comment by kugg** [comment]
This garbage happened again on Davids FF. Ill tell the user to stop using FF
